worker_processes auto;

events {
    worker_connections 1024;
}

http {
    server_tokens off;
    client_max_body_size 10m;
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/javascript;
    gzip_min_length 11024;
    include /etc/nginx/http.d/*.conf;
}