worker_processes auto;

events {
    worker_connections 1024;
}

http {
    server_tokens off;

    client_max_body_size 10m;

    proxy_cache_path /var/cache/nginx/images
                     levels=1:2
                     keys_zone=img_cache:100m
                     max_size=100m
                     inactive=30d
                     use_temp_path=off;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/javascript;
    gzip_min_length 1024;
    gzip_comp_level 5;


    include /etc/nginx/http.d/*.conf;
}