services:
  postgres_db:
    image: postgres:18-alpine
    container_name: ratingup_db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - "5432"
    networks:
      - back-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ratingup_back
    env_file:
      - .env
    depends_on:
      - postgres_db
    expose:
      - "8080"
    networks:
      - back-network
      - front-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ratingup_front
    expose:
      - "4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - front-network
  minio:
    image: minio/minio
    container_name: ratingup_minio
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
      - MINIO_BROWSER_SESSION_DURATION=${MINIO_SESSION}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - back-network
  nginx:
    image: nginx:alpine
    container_name: ratingup_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - back-network
      - front-network
networks:
  back-network:
    driver: bridge
  front-network:
    driver: bridge
volumes:
  minio_data: