services:
  nginx:
    image: nginx:alpine
    container_name: ratingup_proxy
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/http.d:/etc/nginx/http.d:ro
      - nginx_cache:/var/cache/nginx/images
    depends_on:
      - backend
      - frontend
    networks:
      - back-network
      - front-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ratingup_front
    volumes:
      - ./frontend:/app
      - /app/node_modules
    expose:
      - "4200"
    networks:
      - front-network