name: "📄 Documentação"
description: Relatar necessidade de criação ou ajuste em documentação
title: "[DOCS] "
labels: ["documentation"]
body:
  - type: textarea
    id: description
    attributes:
      label: Descrição do que precisa ser documentado/corrigido
      description: Descreva claramente qual documentação está faltando, incorreta ou precisa ser melhorada.
    validations:
      required: true
  - type: input
    id: location
    attributes:
      label: Local
      description: Arquivo, página ou seção específica.
      placeholder: Ex. README.md, seção de Instalação
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Sugestão de conteúdo
      description: Se aplicável, forneça uma sugestão de texto ou estrutura.
    validations:
      required: false
  - type: textarea
    id: acceptance
    attributes:
      label: Critérios de aceite
      description: Condições que devem ser atendidas para considerar a documentação concluída.
      placeholder: |
        - A documentação deve estar atualizada no local especificado.
        - As informações devem estar corretas e consistentes com o funcionamento atual do sistema.
        - O conteúdo deve ser claro e suficiente para o objetivo descrito na Issue.
        - Links, exemplos e instruções devem funcionar corretamente, quando aplicável.
    validations:
      required: true
