-- =============================================
-- Capítulo 1 — Introdução ao Xadrez
-- =============================================

-- O que é o xadrez
INSERT INTO multiple_choice_question (subtopic_id, question_text)
VALUES ((SELECT id FROM subtopics WHERE title = 'O que é o xadrez' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1)), 'Uma das características que diferencia o xadrez de muitos outros jogos é a forma como as partidas são conduzidas. Considerando as informações aprendidas nesse capítulo, qual alternativa descreve corretamente um aspecto fundamental do funcionamento do jogo?');

INSERT INTO multiple_choice_option (question_id, option_text, is_correct) VALUES
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'O que é o xadrez' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'O resultado de uma partida de xadrez depende, em grande parte, de elementos aleatórios, como sorteios ou eventos imprevisíveis que podem favorecer um dos jogadores durante o jogo.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'O que é o xadrez' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'Como todas as informações da partida estão visíveis para ambos os jogadores e não existem cartas escondidas ou dados, os participantes precisam planejar estratégias e antecipar as possíveis ações do adversário.', true),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'O que é o xadrez' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'As peças são distribuídas aleatoriamente no início da partida, o que faz com que cada jogo tenha uma configuração inicial diferente e exija adaptação constante dos jogadores.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'O que é o xadrez' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'Os dois jogadores podem movimentar suas peças ao mesmo tempo durante a partida, desde que não ocupem a mesma casa do tabuleiro.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'O que é o xadrez' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'O jogador que utiliza as peças pretas realiza a primeira jogada da partida, cabendo ao jogador das peças brancas responder aos movimentos do adversário.', false);

-- Objetivo do jogo
INSERT INTO multiple_choice_question (subtopic_id, question_text)
VALUES ((SELECT id FROM subtopics WHERE title = 'Objetivo do jogo' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1)), 'Muitos iniciantes acreditam que o principal objetivo do xadrez é capturar todas as peças do adversário. Entretanto, de acordo com as regras do jogo, a vitória está relacionada diretamente à situação do rei no tabuleiro. Considerando essa informação, qual alternativa descreve corretamente o objetivo principal de uma partida de xadrez?');

INSERT INTO multiple_choice_option (question_id, option_text, is_correct) VALUES
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Objetivo do jogo' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'Capturar todas as peças do adversário antes que ele consiga eliminar as suas, garantindo que o oponente fique sem condições de realizar movimentos.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Objetivo do jogo' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'Acumular o maior número possível de capturas ao longo da partida, independentemente da situação do rei adversário, já que a quantidade de peças determina o vencedor.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Objetivo do jogo' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'Colocar o rei adversário em uma situação de xeque-mate, na qual ele esteja sob ataque e não exista nenhuma possibilidade de escapar, bloquear o ataque ou capturar a peça atacante.', true),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Objetivo do jogo' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'Manter o próprio rei protegido durante toda a partida, evitando qualquer situação de xeque, mesmo que isso impeça a criação de ameaças contra o adversário.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Objetivo do jogo' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'Reduzir a quantidade de peças no tabuleiro até que o adversário não possua material suficiente para continuar a partida, encerrando o jogo automaticamente com uma vitória.', false);

-- História do xadrez
INSERT INTO multiple_choice_question (subtopic_id, question_text)
VALUES ((SELECT id FROM subtopics WHERE title = 'História do xadrez' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1)), 'A história do xadrez envolve transformações ocorridas ao longo de muitos séculos, desde seus primeiros registros até a consolidação das regras utilizadas atualmente. Com base nas informações apresentadas sobre a origem e evolução do jogo, qual alternativa descreve corretamente um aspecto importante da história do xadrez?');

INSERT INTO multiple_choice_option (question_id, option_text, is_correct) VALUES
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'História do xadrez' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'O xadrez surgiu na Europa durante o século XVI já com regras praticamente idênticas às atuais, sendo criado por estudiosos que buscavam desenvolver um jogo voltado exclusivamente para competições.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'História do xadrez' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'O jogo que deu origem ao xadrez moderno foi o Chaturanga, criado na região da atual Índia, e posteriormente difundido para outras regiões, passando por adaptações que contribuíram para a formação do jogo conhecido atualmente.', true),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'História do xadrez' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'A expressão "xeque-mate" foi criada na Índia juntamente com o Chaturanga e sempre teve exatamente o mesmo significado utilizado nas regras modernas do xadrez.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'História do xadrez' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'As peças do Chaturanga não possuíam qualquer relação com elementos militares, sendo representações abstratas criadas apenas para diferenciar os movimentos de cada peça.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'História do xadrez' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'O desenvolvimento do xadrez ocorreu de forma rápida e sem alterações significativas, permanecendo praticamente inalterado desde sua criação até os dias atuais.', false);

-- Como o xadrez se tornou esporte
INSERT INTO multiple_choice_question (subtopic_id, question_text)
VALUES ((SELECT id FROM subtopics WHERE title = 'Como o xadrez se tornou esporte' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1)), 'Ao longo da história, o xadrez passou por diversas transformações até ser reconhecido oficialmente como um esporte. Considerando as informações apresentadas sobre esse processo, qual alternativa descreve corretamente um fator que contribuiu para a consolidação do xadrez como modalidade esportiva?');

INSERT INTO multiple_choice_option (question_id, option_text, is_correct) VALUES
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Como o xadrez se tornou esporte' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'O xadrez passou a ser considerado um esporte logo após sua criação, pois desde o início já possuía regras padronizadas, competições internacionais e uma entidade responsável pela organização do jogo.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Como o xadrez se tornou esporte' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'O reconhecimento esportivo do xadrez ocorreu principalmente devido à eliminação de estratégias complexas, tornando as partidas mais simples e acessíveis para todos os jogadores.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Como o xadrez se tornou esporte' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'Durante o século XIX, o surgimento de torneios, a padronização de regras e peças, além da utilização de relógios para controle de tempo, contribuíram para a formação do modelo competitivo que caracteriza o xadrez moderno.', true),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Como o xadrez se tornou esporte' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'A criação da FIDE teve como principal objetivo substituir as regras tradicionais do xadrez por um sistema completamente novo, diferente daquele utilizado nos séculos anteriores.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Como o xadrez se tornou esporte' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'O Comitê Olímpico Internacional reconhece o xadrez como um esporte físico, considerando que o desempenho dos jogadores depende principalmente de força e resistência muscular.', false);

-- O que é Rating
INSERT INTO multiple_choice_question (subtopic_id, question_text)
VALUES ((SELECT id FROM subtopics WHERE title = 'O que é Rating' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1)), 'O sistema de Rating é uma das ferramentas mais importantes do xadrez moderno, sendo utilizado para medir a força dos jogadores e organizar competições de forma mais equilibrada. Com base nas informações apresentadas sobre o funcionamento do Rating, qual alternativa descreve corretamente uma característica desse sistema?');

INSERT INTO multiple_choice_option (question_id, option_text, is_correct) VALUES
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'O que é Rating' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'O Rating de um jogador permanece fixo durante toda a sua carreira, servindo apenas como um registro histórico do nível que ele possuía quando participou de sua primeira competição oficial.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'O que é Rating' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'A quantidade de pontos ganha ou perdida após uma partida é sempre a mesma, independentemente do resultado obtido ou do nível de habilidade do adversário enfrentado.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'O que é Rating' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'O principal objetivo do Rating é contabilizar a quantidade total de partidas disputadas por um jogador, sem considerar vitórias, derrotas ou empates na pontuação final.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'O que é Rating' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'Sistemas de Rating, como o Elo, ajustam a pontuação dos jogadores de acordo com os resultados das partidas e com a diferença de nível entre os adversários, permitindo uma avaliação mais precisa da habilidade de cada competidor.', true),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'O que é Rating' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'O sistema Glicko substituiu completamente o Elo em todas as competições oficiais da FIDE, tornando-se o único método de classificação utilizado no xadrez mundial.', false);

-- Vocabulário básico do xadrez
INSERT INTO multiple_choice_question (subtopic_id, question_text)
VALUES ((SELECT id FROM subtopics WHERE title = 'Vocabulário básico do xadrez' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1)), 'Durante o aprendizado do xadrez, é comum encontrar termos técnicos utilizados para descrever situações específicas da partida e conceitos estratégicos importantes. Compreender esse vocabulário ajuda os jogadores a interpretar partidas, estudar estratégias e se comunicar de forma mais clara dentro do ambiente enxadrístico. Considerando as definições apresentadas no texto, qual alternativa descreve corretamente um desses termos?');

INSERT INTO multiple_choice_option (question_id, option_text, is_correct) VALUES
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Vocabulário básico do xadrez' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'O desenvolvimento consiste em movimentar as peças para posições mais ativas e úteis ao longo da partida, reduzindo a quantidade de peças sem função estratégica e aumentando a influência sobre o tabuleiro.', true),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Vocabulário básico do xadrez' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'O termo xeque-mate é utilizado para indicar que o rei está sob ataque, mas ainda possui alternativas de defesa, como mover-se para uma casa segura, bloquear o ataque ou capturar a peça atacante.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Vocabulário básico do xadrez' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'O meio-jogo corresponde à etapa final da partida, quando poucas peças permanecem no tabuleiro e os jogadores concentram seus esforços em promover peões e buscar o xeque-mate.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Vocabulário básico do xadrez' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'O empate ocorre quando um jogador captura todas as peças adversárias, impossibilitando qualquer continuação da partida e encerrando o jogo sem vencedor.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Vocabulário básico do xadrez' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'A abertura é a fase da partida em que a maior parte das peças já foi trocada, restando apenas algumas unidades para disputar o controle das casas mais importantes.', false);

-- Vocabulário popular do xadrez
INSERT INTO multiple_choice_question (subtopic_id, question_text)
VALUES ((SELECT id FROM subtopics WHERE title = 'Vocabulário popular do xadrez' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1)), 'Além dos termos técnicos utilizados nas regras oficiais, os jogadores de xadrez também utilizam uma série de expressões informais para comentar partidas, avaliar jogadas e descrever situações psicológicas durante o jogo. Essas expressões são bastante comuns em transmissões ao vivo, clubes online e conversas entre enxadristas. Considerando as definições apresentadas no texto, qual alternativa descreve corretamente um desses termos populares?');

INSERT INTO multiple_choice_option (question_id, option_text, is_correct) VALUES
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Vocabulário popular do xadrez' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'A expressão "tô perdido" é utilizada quando um jogador acredita estar em clara vantagem na partida e considera a vitória praticamente garantida.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Vocabulário popular do xadrez' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'O símbolo "!!", frequentemente chamado de "exclamou duas", é usado para indicar uma jogada excepcional, difícil de encontrar e considerada brilhante pelos analistas.', true),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Vocabulário popular do xadrez' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'O termo "blunder" é empregado para descrever uma sequência de jogadas equilibradas, sem erros significativos cometidos por nenhum dos jogadores.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Vocabulário popular do xadrez' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'A expressão "rei afogado" ocorre quando o rei está em xeque e não possui nenhuma possibilidade de escapar, caracterizando uma vitória imediata do adversário.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Vocabulário popular do xadrez' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 1))), 'O símbolo "?" é utilizado para indicar uma jogada forte e precisa, que melhora significativamente a posição do jogador.', false);

-- =============================================
-- Capítulo 2 — O Tabuleiro e as Peças
-- =============================================

-- Estrutura do tabuleiro
INSERT INTO multiple_choice_question (subtopic_id, question_text)
VALUES ((SELECT id FROM subtopics WHERE title = 'Estrutura do tabuleiro' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2)), 'Antes de aprender o movimento das peças e as estratégias do jogo, é fundamental compreender a estrutura do tabuleiro de xadrez, já que todas as ações da partida acontecem sobre ele. Considerando as características apresentadas sobre a organização do tabuleiro e a disposição inicial das peças, qual alternativa descreve corretamente um aspecto dessa estrutura?');

INSERT INTO multiple_choice_option (question_id, option_text, is_correct) VALUES
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Estrutura do tabuleiro' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'O tabuleiro de xadrez é formado por uma malha de 10 linhas e 10 colunas, totalizando 100 casas que são ocupadas gradualmente ao longo da partida.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Estrutura do tabuleiro' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'Após a montagem inicial, todas as casas do tabuleiro ficam ocupadas por peças, não existindo espaços vazios entre os exércitos dos dois jogadores.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Estrutura do tabuleiro' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'Para que o tabuleiro esteja corretamente orientado, a casa localizada no canto inferior direito deve ser de cor escura para ambos os jogadores.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Estrutura do tabuleiro' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'O tabuleiro possui 64 casas organizadas em uma estrutura 8x8, e as peças são posicionadas nas duas fileiras mais próximas de cada jogador, deixando as fileiras centrais inicialmente vazias.', true),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Estrutura do tabuleiro' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'Cada jogador inicia a partida ocupando apenas uma fileira do tabuleiro, enquanto as demais peças entram em jogo conforme a partida avança.', false);

-- Casas claras e escuras
INSERT INTO multiple_choice_question (subtopic_id, question_text)
VALUES ((SELECT id FROM subtopics WHERE title = 'Casas claras e escuras' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2)), 'Uma das características mais marcantes do tabuleiro de xadrez é o padrão alternado de cores presente em suas casas. Além de contribuir para a aparência visual do tabuleiro, essa organização possui uma função importante durante a partida. Com base nas informações apresentadas sobre as casas claras e escuras, qual alternativa está correta?');

INSERT INTO multiple_choice_option (question_id, option_text, is_correct) VALUES
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Casas claras e escuras' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'As casas do tabuleiro são distribuídas de forma aleatória entre cores claras e escuras, variando de acordo com o material utilizado na fabricação do tabuleiro.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Casas claras e escuras' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'Em torneios oficiais, apenas tabuleiros nas cores preto e branco podem ser utilizados, pois outras combinações de cores não são reconhecidas pelas regras do xadrez.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Casas claras e escuras' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'Embora os tabuleiros possam ser fabricados em diferentes materiais e tonalidades, as casas continuam sendo tratadas na linguagem do xadrez como casas claras e escuras, mantendo uma divisão equilibrada entre ambas.', true),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Casas claras e escuras' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'O padrão alternado de cores existe exclusivamente por razões estéticas, não oferecendo qualquer benefício para a compreensão ou orientação dos jogadores durante a partida.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Casas claras e escuras' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'O tabuleiro de xadrez possui mais casas escuras do que claras, pois essa distribuição facilita a visualização das peças durante o jogo.', false);

-- Colunas, fileiras e diagonais
INSERT INTO multiple_choice_question (subtopic_id, question_text)
VALUES ((SELECT id FROM subtopics WHERE title = 'Colunas, fileiras e diagonais' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2)), 'Para compreender a movimentação das peças no xadrez, é necessário conhecer as diferentes direções que organizam o espaço do tabuleiro. Essas direções formam caminhos específicos utilizados pelas peças durante a partida e ajudam os jogadores a identificar posições e trajetórias. Com base nas definições de colunas, fileiras e diagonais, qual alternativa está correta?');

INSERT INTO multiple_choice_option (question_id, option_text, is_correct) VALUES
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Colunas, fileiras e diagonais' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'As colunas correspondem às linhas horizontais do tabuleiro, enquanto as fileiras representam as linhas verticais que ligam um jogador ao outro.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Colunas, fileiras e diagonais' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'As diagonais são formadas por casas de cores alternadas e possuem sempre o mesmo comprimento, independentemente da região do tabuleiro em que se encontram.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Colunas, fileiras e diagonais' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'Todas as diagonais do tabuleiro possuem exatamente oito casas, pois precisam atravessar toda a extensão do tabuleiro para serem consideradas diagonais válidas.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Colunas, fileiras e diagonais' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'As colunas, fileiras e diagonais possuem a mesma orientação espacial, diferenciando-se apenas pela nomenclatura utilizada pelos enxadristas.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Colunas, fileiras e diagonais' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'As fileiras são linhas horizontais que atravessam o tabuleiro de leste a oeste, enquanto as colunas são linhas verticais que se estendem de um jogador ao outro.', true);

-- Nomeação das casas
INSERT INTO multiple_choice_question (subtopic_id, question_text)
VALUES ((SELECT id FROM subtopics WHERE title = 'Nomeação das casas' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2)), 'Para registrar partidas, estudar posições e permitir uma comunicação precisa entre jogadores, o xadrez utiliza um sistema padronizado de identificação das casas do tabuleiro chamado Notação Algébrica. Esse método atribui um nome único para cada casa a partir da combinação de coordenadas horizontais e verticais. Com base nas informações apresentadas sobre esse sistema, qual alternativa está correta?');

INSERT INTO multiple_choice_option (question_id, option_text, is_correct) VALUES
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Nomeação das casas' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'Na Notação Algébrica, as casas são identificadas pela combinação de números e letras, mas a ordem desses elementos é indiferente, sendo válidas tanto as formas "d4" quanto "4d".', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Nomeação das casas' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'As casas do eixo horizontal são numeradas de 1 a 8, enquanto as do eixo vertical recebem letras de "a" até "h", formando a identificação final de cada casa.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Nomeação das casas' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'A Notação Algébrica utiliza apenas números para identificar as casas, enquanto as letras são reservadas exclusivamente para representar as peças durante o registro das partidas.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Nomeação das casas' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'A identificação das casas é definida a partir do cruzamento dos eixos do tabuleiro, sendo obrigatório escrever primeiro a letra correspondente ao eixo horizontal e depois o número correspondente ao eixo vertical.', true),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Nomeação das casas' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'A orientação utilizada para nomear as casas é baseada na perspectiva do jogador que conduz as peças pretas, independentemente do lado em que o tabuleiro esteja posicionado.', false);

-- Conhecendo as peças
INSERT INTO multiple_choice_question (subtopic_id, question_text)
VALUES ((SELECT id FROM subtopics WHERE title = 'Conhecendo as peças' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2)), 'No xadrez, cada jogador inicia a partida com um conjunto de 16 peças distribuídas em diferentes categorias, cada uma possuindo funções e movimentos específicos. A combinação dessas peças permite a criação de estratégias de ataque, defesa e controle do tabuleiro. Com base nas informações apresentadas sobre as peças do jogo, qual alternativa está correta?');

INSERT INTO multiple_choice_option (question_id, option_text, is_correct) VALUES
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Conhecendo as peças' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'Os peões representam a maior parte das forças de cada jogador, enquanto cavalos, bispos e torres exercem funções táticas importantes em ações ofensivas e defensivas.', true),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Conhecendo as peças' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'A dama é considerada a peça mais importante da partida, pois sua captura encerra imediatamente o jogo e determina a vitória do adversário.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Conhecendo as peças' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'Todos os tipos de peças possuem a mesma quantidade inicial no tabuleiro, diferenciando-se apenas pela forma como podem se movimentar durante a partida.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Conhecendo as peças' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'O rei é a peça com maior alcance de movimento no tabuleiro, sendo utilizado principalmente para liderar ataques contra as peças adversárias.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Conhecendo as peças' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'Cada jogador inicia a partida com 18 peças, incluindo duas damas, dois reis e uma combinação de peças menores distribuídas nas primeiras fileiras.', false);

-- Valor relativo das peças
INSERT INTO multiple_choice_question (subtopic_id, question_text)
VALUES ((SELECT id FROM subtopics WHERE title = 'Valor relativo das peças' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2)), 'Embora a vitória no xadrez seja obtida exclusivamente por meio do xeque-mate, os jogadores utilizam um sistema de valores relativos para avaliar a importância das peças e tomar decisões estratégicas durante a partida. Esse sistema auxilia principalmente na análise de trocas e sacrifícios, permitindo estimar se uma sequência de lances tende a ser favorável ou desfavorável. Com base nas informações apresentadas sobre os valores das peças, qual alternativa está correta?');

INSERT INTO multiple_choice_option (question_id, option_text, is_correct) VALUES
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Valor relativo das peças' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'O valor relativo das peças é definido exclusivamente pela quantidade de casas que elas ocupam no tabuleiro, sem relação com mobilidade ou influência estratégica.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Valor relativo das peças' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'Como o rei possui valor infinito, ele pode ser utilizado em trocas vantajosas desde que a peça capturada possua valor superior ao das demais peças do tabuleiro.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Valor relativo das peças' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'O sistema de valores relativos é utilizado para determinar oficialmente o vencedor da partida quando nenhum dos jogadores consegue aplicar um xeque-mate.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Valor relativo das peças' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'Uma dama possui o mesmo valor relativo de três bispos juntos, o que faz com que qualquer troca entre essas peças seja considerada perfeitamente equilibrada.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Valor relativo das peças' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 2))), 'Capturar uma torre adversária utilizando um cavalo geralmente é considerado uma troca favorável do ponto de vista material, já que a torre possui valor simbólico superior ao do cavalo.', true);


-- =============================================
-- Capítulo 4 — Regras Fundamentais
-- =============================================

-- Tempo
INSERT INTO multiple_choice_question (subtopic_id, question_text)
VALUES ((SELECT id FROM subtopics WHERE title = 'Tempo' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 4)), 'Em muitas competições de xadrez, os jogadores precisam administrar não apenas suas peças e estratégias, mas também o tempo disponível para pensar em cada lance. Para isso, utiliza-se um relógio especial que controla separadamente o tempo de cada participante. Considerando as informações apresentadas sobre o uso do relógio no xadrez, qual alternativa está correta?');

INSERT INTO multiple_choice_option (question_id, option_text, is_correct) VALUES
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Tempo' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 4))), 'O relógio de ambos os jogadores continua contando simultaneamente durante toda a partida, independentemente de quem está realizando a jogada.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Tempo' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 4))), 'Quando um jogador conclui seu movimento, o relógio é pausado definitivamente até que o árbitro autorize o próximo lance.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Tempo' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 4))), 'Caso o tempo de um jogador termine, a partida sempre será encerrada com sua derrota, independentemente da posição das peças restantes no tabuleiro.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Tempo' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 4))), 'O controle de tempo funciona de forma alternada entre os jogadores, e o esgotamento do tempo pode resultar em empate caso o adversário não possua material suficiente para realizar um xeque-mate.', true),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Tempo' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 4))), 'Em partidas com relógio, o vencedor é determinado pelo jogador que possuir mais tempo restante ao final do jogo, mesmo que sofra um xeque-mate antes disso.', false);

-- Empate por repetição
INSERT INTO multiple_choice_question (subtopic_id, question_text)
VALUES ((SELECT id FROM subtopics WHERE title = 'Empate por repetição' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 4)), 'Durante algumas partidas de xadrez, pode acontecer de os jogadores repetirem uma sequência de movimentos várias vezes sem que a posição do tabuleiro apresente mudanças significativas. Para evitar que a partida se prolongue indefinidamente sem progresso real, as regras do xadrez preveem uma situação especial de empate. Com base nesse conceito, qual alternativa descreve corretamente o empate por repetição?');

INSERT INTO multiple_choice_option (question_id, option_text, is_correct) VALUES
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Empate por repetição' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 4))), 'Ocorre quando os jogadores repetem exatamente o mesmo movimento durante dez turnos consecutivos, independentemente da posição das demais peças no tabuleiro.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Empate por repetição' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 4))), 'Acontece quando uma mesma posição é repetida três vezes ao longo da partida, com as mesmas possibilidades de movimento para ambos os jogadores, permitindo que o empate seja reivindicado.', true),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Empate por repetição' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 4))), 'É declarado automaticamente quando um dos jogadores move a mesma peça mais de três vezes seguidas sem realizar capturas.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Empate por repetição' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 4))), 'Surge quando restam poucas peças no tabuleiro e nenhum dos jogadores consegue realizar um xeque-mate imediato.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Empate por repetição' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 4))), 'Ocorre apenas quando os reis são as únicas peças restantes no tabuleiro e passam a repetir movimentos entre as mesmas casas.', false);

-- Regra dos 50 lances
INSERT INTO multiple_choice_question (subtopic_id, question_text)
VALUES ((SELECT id FROM subtopics WHERE title = 'Regra dos 50 lances' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 4)), 'Além das formas tradicionais de vitória e empate, o xadrez possui regras destinadas a impedir que uma partida continue por muito tempo sem qualquer progresso efetivo. Uma dessas regras é conhecida como Regra dos 50 Lances. Considerando seu funcionamento, qual alternativa está correta?');

INSERT INTO multiple_choice_option (question_id, option_text, is_correct) VALUES
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Regra dos 50 lances' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 4))), 'A regra determina empate quando cada jogador realiza exatamente 50 movimentos durante toda a partida, independentemente do que tenha acontecido anteriormente.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Regra dos 50 lances' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 4))), 'A contagem dos 50 lances é reiniciada sempre que ocorre um xeque, mesmo que nenhuma peça seja capturada ou que nenhum peão seja movimentado.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Regra dos 50 lances' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 4))), 'A Regra dos 50 Lances pode levar ao empate quando ocorrem cinquenta lances consecutivos de cada lado sem movimentação de peões e sem capturas de peças.', true),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Regra dos 50 lances' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 4))), 'A regra é aplicada apenas em finais de partida com poucas peças no tabuleiro, não podendo ser utilizada em posições mais complexas.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Regra dos 50 lances' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 4))), 'Sempre que a contagem atinge 50 lances, o jogador com mais peças no tabuleiro é declarado vencedor automaticamente.', false);


-- =============================================
-- Capítulo 6 — Princípios Básicos de Abertura
-- =============================================

-- Não mover a mesma peça várias vezes
INSERT INTO multiple_choice_question (subtopic_id, question_text)
VALUES ((SELECT id FROM subtopics WHERE title = 'Não mover a mesma peça várias vezes' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 6)), 'Durante a abertura, um dos principais objetivos do jogador é desenvolver suas peças de maneira eficiente. Como cada lance representa um recurso valioso, decisões inadequadas podem atrasar o desenvolvimento e permitir que o adversário assuma a iniciativa da partida. Considerando esse princípio, qual alternativa descreve corretamente a razão pela qual normalmente se evita mover a mesma peça várias vezes nos primeiros lances?');

INSERT INTO multiple_choice_option (question_id, option_text, is_correct) VALUES
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Não mover a mesma peça várias vezes' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 6))), 'Porque as regras oficiais do xadrez limitam a quantidade de vezes que uma mesma peça pode ser movimentada durante a fase de abertura.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Não mover a mesma peça várias vezes' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 6))), 'Porque repetir movimentos com a mesma peça costuma atrasar o desenvolvimento das demais peças, permitindo que o adversário ganhe espaço, controle do centro e atividade mais rapidamente.', true),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Não mover a mesma peça várias vezes' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 6))), 'Porque uma peça que já foi movimentada na abertura não pode participar de ataques até que todas as outras peças tenham sido desenvolvidas.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Não mover a mesma peça várias vezes' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 6))), 'Porque mover a mesma peça mais de uma vez nos primeiros lances resulta automaticamente em perda de material ou desvantagem estratégica irreversível.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Não mover a mesma peça várias vezes' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 6))), 'Porque o desenvolvimento correto exige que todas as peças sejam movimentadas exatamente uma vez antes que qualquer uma delas possa se mover novamente.', false);


-- Padronização de aberturas
INSERT INTO multiple_choice_question (subtopic_id, question_text)
VALUES ((SELECT id FROM subtopics WHERE title = 'Padronização de aberturas' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 6)), 'No estudo do xadrez, as aberturas são frequentemente apresentadas como modelos de desenvolvimento que ajudam os jogadores a iniciar a partida de forma organizada. Entretanto, o texto destaca que o aprendizado das aberturas não deve se limitar à memorização de sequências de lances. Com base nessa ideia, qual alternativa expressa corretamente o papel da padronização das aberturas no aprendizado do jogo?');

INSERT INTO multiple_choice_option (question_id, option_text, is_correct) VALUES
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Padronização de aberturas' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 6))), 'As aberturas padronizadas eliminam a necessidade de compreender princípios estratégicos, pois basta repetir exatamente os movimentos estudados para obter vantagem.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Padronização de aberturas' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 6))), 'O principal objetivo das aberturas é permitir que o jogador memorize longas sequências de lances sem precisar analisar a posição criada no tabuleiro.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Padronização de aberturas' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 6))), 'As aberturas funcionam como modelos de desenvolvimento baseados em princípios gerais do xadrez, ajudando o jogador a controlar o centro, desenvolver as peças e proteger o rei de forma mais consistente.', true),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Padronização de aberturas' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 6))), 'Estudar aberturas é útil apenas para jogadores profissionais, já que iniciantes não conseguem aplicar os padrões estratégicos presentes nesses sistemas.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Padronização de aberturas' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 6))), 'A padronização das aberturas existe para garantir que todas as partidas comecem exatamente com os mesmos movimentos, reduzindo a variedade de posições possíveis no início do jogo.', false);

-- =============================================
-- Capítulo 7 — Noções Básicas de Tática
-- =============================================

-- Estrutura de peões
INSERT INTO multiple_choice_question (subtopic_id, question_text)
VALUES ((SELECT id FROM subtopics WHERE title = 'Estrutura de peões' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 7)), 'Embora os peões sejam as peças de menor valor material no xadrez, a forma como eles estão organizados no tabuleiro exerce grande influência sobre a qualidade de uma posição. Esse conjunto de relações entre os peões é conhecido como estrutura de peões e costuma orientar muitos planos estratégicos ao longo da partida. Com base nas informações apresentadas sobre esse conceito, qual alternativa está correta?');

INSERT INTO multiple_choice_option (question_id, option_text, is_correct) VALUES
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Estrutura de peões' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 7))), 'A estrutura de peões possui pouca influência sobre a partida, pois os peões normalmente são trocados rapidamente e deixam de afetar o posicionamento das demais peças.', true),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Estrutura de peões' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 7))), 'Como os peões podem retornar para casas anteriormente ocupadas, erros na movimentação dessas peças costumam ser facilmente corrigidos ao longo da partida.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Estrutura de peões' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 7))), 'Uma boa estrutura de peões pode contribuir para o controle de espaço, a proteção do rei e a coordenação das demais peças, enquanto estruturas frágeis podem gerar pontos vulneráveis difíceis de defender.', true),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Estrutura de peões' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 7))), 'A principal função da estrutura de peões é aumentar o valor material do jogador, já que peões bem posicionados passam a valer mais pontos do que as peças menores.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Estrutura de peões' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 7))), 'Acumular vários peões na mesma coluna é geralmente considerado um dos principais objetivos estratégicos da abertura, pois fortalece a defesa da posição.', false);

-- CCT
INSERT INTO multiple_choice_question (subtopic_id, question_text)
VALUES ((SELECT id FROM subtopics WHERE title = 'CCT (Checks, Captures, Threats)' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 7)), 'Durante uma partida de xadrez, muitos erros acontecem porque o jogador realiza movimentos sem analisar adequadamente as possibilidades imediatas da posição. Para ajudar nesse processo, existe o método CCT, que orienta a busca por lances forçados e recursos táticos antes da elaboração de planos mais complexos. Considerando as características desse método, qual alternativa está correta?');

INSERT INTO multiple_choice_option (question_id, option_text, is_correct) VALUES
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'CCT (Checks, Captures, Threats)' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 7))), 'O método CCT recomenda que o jogador ignore xeques e capturas durante a análise inicial, concentrando-se apenas em planos de longo prazo.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'CCT (Checks, Captures, Threats)' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 7))), 'O objetivo principal do CCT é memorizar sequências de abertura, permitindo que o jogador reproduza movimentos conhecidos sem necessidade de cálculo.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'CCT (Checks, Captures, Threats)' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 7))), 'O CCT é utilizado apenas em finais de partida, quando restam poucas peças e as ameaças táticas se tornam mais fáceis de identificar.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'CCT (Checks, Captures, Threats)' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 7))), 'O método incentiva o jogador a verificar primeiro possíveis xeques, capturas e ameaças, já que esses lances frequentemente exigem respostas imediatas e podem esconder oportunidades táticas importantes.', true),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'CCT (Checks, Captures, Threats)' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 7))), 'A sigla CCT representa um sistema de avaliação material que atribui valores numéricos às peças para determinar qual jogador está em vantagem.', false);

-- =============================================
-- Capítulo 8 — Como desenvolver o meio-jogo
-- =============================================

-- O que é o meio-jogo
INSERT INTO multiple_choice_question (subtopic_id, question_text)
VALUES ((SELECT id FROM subtopics WHERE title = 'O que é o meio-jogo' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 8)), 'Após a fase de abertura, quando as peças já foram desenvolvidas e os jogadores começam a executar ideias mais elaboradas, a partida entra em uma etapa conhecida como meio-jogo. Essa fase é considerada uma das mais importantes do xadrez, pois concentra grande parte das decisões estratégicas e táticas que influenciam o resultado final da partida. Com base nas características apresentadas sobre o meio-jogo, qual alternativa está correta?');

INSERT INTO multiple_choice_option (question_id, option_text, is_correct) VALUES
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'O que é o meio-jogo' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 8))), 'O meio-jogo é uma fase em que a maioria das peças já foi capturada, restando apenas os reis e alguns peões para disputar o resultado da partida.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'O que é o meio-jogo' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 8))), 'Durante o meio-jogo, os jogadores costumam seguir sequências fixas de movimentos previamente decoradas, o que reduz significativamente a necessidade de cálculo e análise da posição.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'O que é o meio-jogo' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 8))), 'O meio-jogo é caracterizado pela grande atividade das peças, pela realização de ataques, trocas e disputas por espaço, exigindo análise constante das oportunidades e dos riscos presentes na posição.', true),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'O que é o meio-jogo' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 8))), 'Nessa fase da partida, os erros têm pouca influência sobre o resultado, pois ainda existem muitas peças capazes de corrigir qualquer problema criado por um lance impreciso.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'O que é o meio-jogo' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 8))), 'O principal objetivo do meio-jogo é apenas preparar o tabuleiro para o final, sem a necessidade de criar ameaças ou desenvolver planos estratégicos relevantes.', false);

-- Planos no meio-jogo
INSERT INTO multiple_choice_question (subtopic_id, question_text)
VALUES ((SELECT id FROM subtopics WHERE title = 'Planos no meio-jogo' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 8)), 'Uma das habilidades mais importantes para evoluir no xadrez é aprender a criar planos durante o meio-jogo. Em vez de realizar movimentos isolados ou apenas reagir às ações do adversário, o jogador deve procurar organizar suas peças em torno de objetivos estratégicos que façam sentido para a posição existente no tabuleiro. Considerando as informações apresentadas sobre a elaboração de planos, qual alternativa está correta?');

INSERT INTO multiple_choice_option (question_id, option_text, is_correct) VALUES
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Planos no meio-jogo' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 8))), 'Um plano no meio-jogo consiste em memorizar uma sequência fixa de movimentos que deve ser executada independentemente das mudanças ocorridas na posição.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Planos no meio-jogo' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 8))), 'A criação de planos depende da análise de fatores como segurança dos reis, estrutura de peões, posicionamento das peças e controle de espaço, permitindo que o jogador defina objetivos coerentes para a posição.', true),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Planos no meio-jogo' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 8))), 'Durante o meio-jogo, o melhor método é responder exclusivamente às ameaças do adversário, evitando estabelecer metas próprias para não comprometer a flexibilidade da posição.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Planos no meio-jogo' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 8))), 'Os planos estratégicos só passam a ter importância quando a partida chega ao final, pois o meio-jogo é dominado apenas por cálculos táticos de curto prazo.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Planos no meio-jogo' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 8))), 'Um plano eficiente deve sempre buscar o ataque direto ao rei adversário, independentemente das características específicas da posição no tabuleiro.', false);

-- Ataque ao rei
INSERT INTO multiple_choice_question (subtopic_id, question_text)
VALUES ((SELECT id FROM subtopics WHERE title = 'Ataque ao rei' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 8)), 'Entre os diversos planos possíveis durante o meio-jogo, o ataque ao rei adversário é um dos mais conhecidos e perigosos. Esse tipo de estratégia busca explorar fraquezas na posição inimiga e criar ameaças que podem culminar em um xeque-mate. Entretanto, para que a ofensiva tenha sucesso, é necessário que as peças estejam coordenadas e que existam condições favoráveis para iniciar o ataque. Com base no texto, qual alternativa descreve corretamente uma característica do ataque ao rei?');

INSERT INTO multiple_choice_option (question_id, option_text, is_correct) VALUES
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Ataque ao rei' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 8))), 'Um ataque ao rei costuma ser mais eficiente quando o jogador inicia a ofensiva rapidamente, mesmo que suas peças ainda não estejam desenvolvidas ou coordenadas.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Ataque ao rei' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 8))), 'Como a vantagem material é sempre mais importante do que a segurança do rei, sacrificar peças para abrir linhas de ataque normalmente é considerado um erro estratégico.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Ataque ao rei' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 8))), 'O ataque ao rei geralmente se torna mais promissor quando existem fraquezas próximas à posição defensiva do adversário, permitindo que as peças ofensivas aumentem a pressão sobre essa região.', true),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Ataque ao rei' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 8))), 'Torres, damas, bispos e cavalos possuem pouca utilidade em ataques ao rei, sendo os peões as únicas peças realmente relevantes nesse tipo de operação estratégica.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Ataque ao rei' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 8))), 'Um rei vulnerável não altera significativamente a avaliação da posição, desde que o jogador atacado possua mais material do que seu adversário.', false);

-- Peças boas vs ruins
INSERT INTO multiple_choice_question (subtopic_id, question_text)
VALUES ((SELECT id FROM subtopics WHERE title = 'Peças boas vs ruins' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 8)), 'Durante o meio-jogo, não basta apenas contar a quantidade de material presente no tabuleiro. A eficiência real de uma peça também depende de sua capacidade de participar ativamente da posição. Por esse motivo, enxadristas costumam utilizar os conceitos de peças boas e peças ruins para avaliar a qualidade do posicionamento das próprias forças. Com base nas informações apresentadas sobre esse tema, qual alternativa está correta?');

INSERT INTO multiple_choice_option (question_id, option_text, is_correct) VALUES
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Peças boas vs ruins' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 8))), 'Uma peça é considerada boa apenas quando possui valor material elevado, independentemente de estar ativa, bloqueada ou distante das regiões importantes do tabuleiro.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Peças boas vs ruins' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 8))), 'O conceito de peças boas e ruins é utilizado exclusivamente para bispos e cavalos, não podendo ser aplicado às demais peças do jogo.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Peças boas vs ruins' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 8))), 'Uma peça ruim é aquela que já realizou muitas movimentações durante a partida, enquanto uma peça boa é aquela que permaneceu na mesma casa desde a abertura.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Peças boas vs ruins' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 8))), 'A qualidade de uma peça depende principalmente de sua atividade e influência sobre a posição, de modo que uma peça teoricamente mais fraca pode ser mais útil do que uma peça de maior valor que esteja limitada ou mal posicionada.', true),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Peças boas vs ruins' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 8))), 'Como o material é o fator mais importante do xadrez, o posicionamento das peças exerce pouca influência na avaliação de uma posição quando ambos os jogadores possuem a mesma quantidade de peças.', false);


-- =============================================
-- Capítulo 9 — Formas de ganhar o final de um jogo
-- =============================================

-- O que é o final
INSERT INTO multiple_choice_question (subtopic_id, question_text)
VALUES ((SELECT id FROM subtopics WHERE title = 'O que é o final' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 9)), 'Após a abertura e o meio-jogo, a partida de xadrez entra em sua fase final, conhecida simplesmente como final. Nessa etapa, a quantidade reduzida de peças modifica profundamente a dinâmica do jogo, tornando alguns conceitos mais importantes do que em fases anteriores. Considerando as características apresentadas sobre os finais, qual alternativa está correta?');

INSERT INTO multiple_choice_option (question_id, option_text, is_correct) VALUES
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'O que é o final' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 9))), 'Durante os finais, o rei continua desempenhando apenas uma função defensiva, devendo permanecer afastado da ação para evitar riscos desnecessários.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'O que é o final' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 9))), 'Como existem poucas peças no tabuleiro, erros cometidos durante o final costumam ter pouca influência sobre o resultado da partida e podem ser facilmente corrigidos.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'O que é o final' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 9))), 'Nos finais, vantagens pequenas perdem importância estratégica, já que a redução do material dificulta a transformação de uma vantagem em vitória.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'O que é o final' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 9))), 'O final é uma fase mais técnica da partida, na qual o rei se torna mais ativo e pequenas vantagens, como um peão extra, podem ser suficientes para decidir o resultado do jogo.', true),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'O que é o final' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 9))), 'A principal característica dos finais é a presença de muitas peças atacando simultaneamente, o que torna essa fase mais complexa taticamente do que o meio-jogo.', false);

-- Tipos de final
INSERT INTO multiple_choice_question (subtopic_id, question_text)
VALUES ((SELECT id FROM subtopics WHERE title = 'Tipos de final' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 9)), 'Embora todos os finais ocorram quando restam poucas peças no tabuleiro, eles podem apresentar características bastante diferentes dependendo do material disponível para cada jogador. Por esse motivo, enxadristas estudam diversos tipos de finais e aprendem técnicas específicas para cada situação. Com base nas informações apresentadas sobre os tipos de final, qual alternativa está correta?');

INSERT INTO multiple_choice_option (question_id, option_text, is_correct) VALUES
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Tipos de final' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 9))), 'Todos os finais seguem exatamente os mesmos princípios estratégicos, independentemente das peças restantes no tabuleiro, tornando desnecessário estudar categorias específicas.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Tipos de final' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 9))), 'Os finais de peões costumam depender bastante de cálculo preciso, enquanto os finais de torres são conhecidos por sua complexidade e pela capacidade das torres de atuar à distância.', true),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Tipos de final' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 9))), 'Os finais de torres são considerados os mais simples do xadrez, pois a mobilidade da torre reduz significativamente a quantidade de possibilidades existentes.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Tipos de final' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 9))), 'O conhecimento dos diferentes tipos de final é útil apenas quando a partida já entrou nessa fase, não influenciando decisões tomadas durante o meio-jogo.', false),
                                                                              ((SELECT id FROM multiple_choice_question WHERE subtopic_id = (SELECT id FROM subtopics WHERE title = 'Tipos de final' AND chapter_id = (SELECT id FROM chapters WHERE display_order = 9))), 'Finais com bispos, cavalos ou damas são extremamente raros e não exigem conhecimentos específicos sobre as características dessas peças.', false);
