spring.datasource.url=jdbc:postgresql://localhost:5432/ratingup
spring.datasource.username=postgres
spring.datasource.password=5!aD@K8$uT3q
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect