# Configurações Básicas
spring.application.name=${APP_NAME}
server.port=${SERVER_PORT}

# Configurações Banco de Dados
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.flyway.validate-migration-naming=true

# Configurações MinIO
MINIO_ROOT_USER=${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
MINIO_BROWSER_SESSION_DURATION: ${MINIO_ROOT_SESSION}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Configurações de Segurança
#spring.security.user.name=admin
#spring.security.user.password=123456
api.security.token.secret=${JWT_SECRET}

# Configurações do EmailSender
spring.mail.host=${EMAIL_HOST}
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.name=${EMAIL_NAME}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Configurações do Swagger
springdoc.swagger-ui.config-url=/api/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/api/v3/api-docs