spring.application.name=Ratingup
spring.datasource.url=jdbc:postgresql://postgres_db:5432/ratingup
spring.datasource.username=postgres
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=admin
spring.security.user.password=123456

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always